Vagrant.configure("2") do |config|
	
	config.vm.box = "dummy"

		
	config.vm.define :gestionImagenes do |gestionImagenes|
		gestionImagenes.vm.host_name = "gestionImagenes"
			
		gestionImagenes.vm.provider :aws do |aws, override|
			aws.access_key_id = ENV['ACCESS_KEY_ID']
			aws.secret_access_key = ENV['ACCESS_KEY_SECRET']
			aws.keypair_name = ENV['ACCESS_KEYPAIR']
			aws.ami = "ami-01f05461"
			aws.instance_type = "t2.micro"
			aws.security_groups = ["vagrant"]
			aws.region = 'us-west-2'
			aws.availability_zone = "us-west-2a" 
			aws.tags = {
				'Name' => 'Instancia FunnyBot gestion imagenes',
				'Environment' => 'vagrant'
			}
			
			override.ssh.username = "ubuntu"
			override.ssh.private_key_path = "~/Escritorio/parClavesVagrantSSH.pem"
		end
		
		gestionImagenes.vm.provision :ansible do |ansible|
			ansible.sudo = true
			ansible.playbook = "../../Provisionamiento/Ansible/playbook.yml"
		end
		
		gestionImagenes.vm.provider :docker do |docker|
			docker.build_image = "../../Dockerfile"
		end
	end
		
	config.vm.define :gestionChistes do |gestionChistes|
		gestionChistes.vm.host_name = "gestionChistes"
			
		gestionChistes.vm.provider :aws do |aws, override|
			aws.access_key_id = "AKIAIB2FUS5YTGPQ7VIQ"
			aws.secret_access_key = "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"
			aws.keypair_name = "parClavesVagrantSSH"
			aws.ami = "ami-01f05461"
			aws.instance_type = "t2.micro"
			aws.security_groups = ["vagrant"]
			aws.region = 'us-west-2'
			aws.availability_zone = "us-west-2a"
			aws.tags = {
				'Name' => 'Instancia FunnyBot gestion chistes',
				'Environment' => 'vagrant'
			}
			 
			override.ssh.username = "ubuntu"
			override.ssh.private_key_path = "~/Escritorio/parClavesVagrantSSH.pem"
		end
		
		gestionChistes.vm.provision :ansible do |ansible|
			ansible.sudo = true
			ansible.playbook = "../../Provisionamiento/Ansible/playbook.yml"
		end
	end
end
